### ISSUE TITLE
Trying to get property 'username' of non-object (View: C:\inetpub\wwwroot\resources\views\GoldFish\components\news.blade.php) (View: C:\inetpub\wwwroot\resources\views\GoldFish\components\news.blade.php)

### ISSUE THREAD

**Issue by Mickyc94** [Laynester/GoldFish#12]
Trying to get property 'username' of non-object (View: C:\inetpub\wwwroot\resources\views\GoldFish\components\news.blade.php) (View: C:\inetpub\wwwroot\resources\views\GoldFish\components\news.blade.php)

![Screenshot_2020-02-03 Whoops There was an error ](https://user-images.githubusercontent.com/979191/73619450-59a5e500-4625-11ea-8c7b-c982c925c4e1.png)

DOES IT ON BOTH XAMPP AND IIS. Not sure if its something I have done wrong during setup or not.

**Comment by HairoDev** [comment]
It's not just you. I have the same problem, and didn't find any solution yet.

**Comment by HairoDev** [comment]
Try to go into your database and find the created account from installation. Change the id of the created account to 1.
This should fix it, for me at least. I just found it out.

**Comment by Mickyc94** [comment]
> 
> 
> Try to go into your database and find the created account from installation. Change the id of the created account to 1.
> This should fix it, for me at least. I just found it out.

Just gives me a new error, similar but now "navbar.blade.php"

**Comment by HairoDev** [comment]
You probably updated to Laravel 6 I assume.
Since helpers are removed, you need to specifically install them.
Open your terminal and cd to your files and run:

> composer require laravel/helpers

hopefully that works for you.

**Comment by HairoDev** [comment]
I'm glad that I was able to help you :)

**Comment by Mickyc94** [comment]
> 
> 
> I'm glad that I was able to help you :)

thankyou for your help, not alot of activity in this community lately or grateful people around these days so thankyou.
